minor changes

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -66,9 +66,21 @@ jobs:
       - name: Upload package to S3 and deploy
         env:
           S3_BUCKET: ${{ secrets.S3_BUCKET }}
+          ACM_CERTIFICATE_ARN: ${{ secrets.ACM_CERTIFICATE_ARN }}
+          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
         run: |
           if [ -z "$S3_BUCKET" ]; then
             echo "S3_BUCKET secret is required."
+            exit 1
+          fi
+          
+          if [ -z "$ACM_CERTIFICATE_ARN" ]; then
+            echo "ACM_CERTIFICATE_ARN secret is required."
+            exit 1
+          fi
+          
+          if [ -z "$CUSTOM_DOMAIN_NAME" ]; then
+            echo "CUSTOM_DOMAIN_NAME secret is required."
             exit 1
           fi
 
@@ -97,8 +109,8 @@ jobs:
               S3Key="$S3_FILE_NAME" \
               S3Bucket="$S3_BUCKET" \
               StageName="$STAGE_NAME" \
-              AcmCertificateArn="${{ secrets.ACM_CERTIFICATE_ARN }}" \
-              CustomDomainName="${{ secrets.CUSTOM_DOMAIN_NAME }}" \
-              HostedZoneId="${{ secrets.HOSTED_ZONE_ID }}"
+              AcmCertificateArn="$ACM_CERTIFICATE_ARN" \
+              CustomDomainName="$CUSTOM_DOMAIN_NAME" \
+              Route53HostedZoneId="${{ secrets.ROUTE53_HOSTED_ZONE_ID }}"
 
 
